/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tiian_flom_FlomHandle */

#ifndef _Included_org_tiian_flom_FlomHandle
#define _Included_org_tiian_flom_FlomHandle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    newFlomHandle
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_tiian_flom_FlomHandle_newFlomHandle
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    deleteFlomHandle
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_tiian_flom_FlomHandle_deleteFlomHandle
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_tiian_flom_FlomException */

#ifndef _Included_org_tiian_flom_FlomException
#define _Included_org_tiian_flom_FlomException
#ifdef __cplusplus
extern "C" {
#endif
#undef org_tiian_flom_FlomException_serialVersionUID
#define org_tiian_flom_FlomException_serialVersionUID -3042686055658047285LL
#undef org_tiian_flom_FlomException_serialVersionUID
#define org_tiian_flom_FlomException_serialVersionUID -3387516993124229948LL
/*
 * Class:     org_tiian_flom_FlomException
 * Method:    getReturnCodeText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_tiian_flom_FlomException_getReturnCodeText
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
