/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tiian_flom_FlomHandle */

#ifndef _Included_org_tiian_flom_FlomHandle
#define _Included_org_tiian_flom_FlomHandle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    newJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_newJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    deleteJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tiian_flom_FlomHandle_deleteJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    lockJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_lockJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    unlockJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_unlockJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getLockedElementJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_tiian_flom_FlomHandle_getLockedElementJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getDiscoveryAttemptsJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_getDiscoveryAttemptsJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setDiscoveryAttemptsJNI
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setDiscoveryAttemptsJNI
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getDiscoveryTimeoutJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_getDiscoveryTimeoutJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setDiscoveryTimeoutJNI
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setDiscoveryTimeoutJNI
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getDiscoveryTtlJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_getDiscoveryTtlJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setDiscoveryTtlJNI
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setDiscoveryTtlJNI
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getLockModeJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_getLockModeJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setLockModeJNI
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setLockModeJNI
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getMulticastAddressJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_tiian_flom_FlomHandle_getMulticastAddressJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setMulticastAddressJNI
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setMulticastAddressJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getMulticastPortJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_getMulticastPortJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setMulticastPortJNI
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setMulticastPortJNI
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getResourceCreateJNI
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_tiian_flom_FlomHandle_getResourceCreateJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setResourceCreateJNI
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setResourceCreateJNI
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getResourceIdleLifespanJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_getResourceIdleLifespanJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setResourceIdleLifespanJNI
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setResourceIdleLifespanJNI
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getResourceNameJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_tiian_flom_FlomHandle_getResourceNameJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setResourceNameJNI
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setResourceNameJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getResourceQuantityJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_getResourceQuantityJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setResourceQuantityJNI
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setResourceQuantityJNI
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getResourceTimeoutJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_getResourceTimeoutJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setResourceTimeoutJNI
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setResourceTimeoutJNI
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getSocketNameJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_tiian_flom_FlomHandle_getSocketNameJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setSocketNameJNI
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setSocketNameJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getTraceFilenameJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_tiian_flom_FlomHandle_getTraceFilenameJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setTraceFilenameJNI
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setTraceFilenameJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getUnicastAddressJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_tiian_flom_FlomHandle_getUnicastAddressJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setUnicastAddressJNI
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setUnicastAddressJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getUnicastPortJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_getUnicastPortJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setUnicastPortJNI
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setUnicastPortJNI
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_tiian_flom_FlomErrorCodes */

#ifndef _Included_org_tiian_flom_FlomErrorCodes
#define _Included_org_tiian_flom_FlomErrorCodes
#ifdef __cplusplus
extern "C" {
#endif
#undef org_tiian_flom_FlomErrorCodes_FLOM_ES_REQUESTER_CANT_WAIT
#define org_tiian_flom_FlomErrorCodes_FLOM_ES_REQUESTER_CANT_WAIT 96L
#undef org_tiian_flom_FlomErrorCodes_FLOM_ES_UNABLE_TO_EXECUTE_COMMAND
#define org_tiian_flom_FlomErrorCodes_FLOM_ES_UNABLE_TO_EXECUTE_COMMAND 97L
#undef org_tiian_flom_FlomErrorCodes_FLOM_ES_RESOURCE_BUSY
#define org_tiian_flom_FlomErrorCodes_FLOM_ES_RESOURCE_BUSY 98L
#undef org_tiian_flom_FlomErrorCodes_FLOM_ES_GENERIC_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_ES_GENERIC_ERROR 99L
#undef org_tiian_flom_FlomErrorCodes_FLOM_ES_OK
#define org_tiian_flom_FlomErrorCodes_FLOM_ES_OK 0L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_API_IMMUTABLE_HANDLE
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_API_IMMUTABLE_HANDLE 11L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_ELEMENT_NAME_NOT_AVAILABLE
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_ELEMENT_NAME_NOT_AVAILABLE 10L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_NETWORK_TIMEOUT
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_NETWORK_TIMEOUT 9L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_CONNECTION_CLOSED
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_CONNECTION_CLOSED 8L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_CONNECTION_REFUSED
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_CONNECTION_REFUSED 7L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_LOCK_IMPOSSIBLE
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_LOCK_IMPOSSIBLE 6L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_LOCK_CANT_WAIT
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_LOCK_CANT_WAIT 5L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_LOCK_BUSY
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_LOCK_BUSY 4L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_LOCK_CANT_LOCK
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_LOCK_CANT_LOCK 3L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_LOCK_WAIT_RESOURCE
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_LOCK_WAIT_RESOURCE 2L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_LOCK_ENQUEUED
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_LOCK_ENQUEUED 1L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_OK
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_OK 0L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_INTERNAL_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_INTERNAL_ERROR -1L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_DAEMON_NOT_STARTED
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_DAEMON_NOT_STARTED -2L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_NETWORK_EVENT_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_NETWORK_EVENT_ERROR -3L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_NULL_OBJECT
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_NULL_OBJECT -4L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_INVALID_OPTION
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_INVALID_OPTION -5L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_OBJ_CORRUPTED
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_OBJ_CORRUPTED -6L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_OUT_OF_RANGE
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_OUT_OF_RANGE -7L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_INVALID_PREFIX_SIZE
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_INVALID_PREFIX_SIZE -8L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_BUFFER_OVERFLOW
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_BUFFER_OVERFLOW -9L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_INVALID_MSG_LENGTH
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_INVALID_MSG_LENGTH -10L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_INVALID_PROPERTY_VALUE
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_INVALID_PROPERTY_VALUE -11L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_CONTAINER_FULL
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_CONTAINER_FULL -12L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_PROTOCOL_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_PROTOCOL_ERROR -13L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_INVALID_RESOURCE_NAME
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_INVALID_RESOURCE_NAME -14L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_PROTOCOL_LEVEL_MISMATCH
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_PROTOCOL_LEVEL_MISMATCH -15L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_MSG_DESERIALIZE_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_MSG_DESERIALIZE_ERROR -16L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_API_INVALID_SEQUENCE
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_API_INVALID_SEQUENCE -17L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_ACCEPT_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_ACCEPT_ERROR -100L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_BIND_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_BIND_ERROR -101L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_CHDIR_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_CHDIR_ERROR -102L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_CLOSE_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_CLOSE_ERROR -103L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_CONNECT_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_CONNECT_ERROR -104L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_EXECVP_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_EXECVP_ERROR -105L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_FCNTL_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_FCNTL_ERROR -106L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_FORK_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_FORK_ERROR -107L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_GETADDRINFO_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_GETADDRINFO_ERROR -108L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_GETNAMEINFO_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_GETNAMEINFO_ERROR -109L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_GETSOCKNAME_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_GETSOCKNAME_ERROR -110L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_GETSOCKOPT_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_GETSOCKOPT_ERROR -111L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_LISTEN_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_LISTEN_ERROR -112L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_MALLOC_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_MALLOC_ERROR -113L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_PIPE_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_PIPE_ERROR -114L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_POLL_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_POLL_ERROR -115L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_READ_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_READ_ERROR -116L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_RECV_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_RECV_ERROR -117L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_RECVFROM_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_RECVFROM_ERROR -118L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_REGCOMP_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_REGCOMP_ERROR -119L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_REGEXEC_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_REGEXEC_ERROR -120L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_SEND_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_SEND_ERROR -121L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_SENDTO_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_SENDTO_ERROR -122L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_SETSID_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_SETSID_ERROR -123L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_SETSOCKOPT_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_SETSOCKOPT_ERROR -124L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_SIGACTION_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_SIGACTION_ERROR -125L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_SIGNAL_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_SIGNAL_ERROR -126L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_SOCKET_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_SOCKET_ERROR -127L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_SNPRINTF_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_SNPRINTF_ERROR -128L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_UNLINK_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_UNLINK_ERROR -129L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_WAIT_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_WAIT_ERROR -130L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_WRITE_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_WRITE_ERROR -131L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_G_ARRAY_NEW_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_G_ARRAY_NEW_ERROR -200L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_G_BASE64_DECODE_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_G_BASE64_DECODE_ERROR -201L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_G_BASE64_ENCODE_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_G_BASE64_ENCODE_ERROR -202L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_G_KEY_FILE_LOAD_FROM_FILE_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_G_KEY_FILE_LOAD_FROM_FILE_ERROR -203L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_G_KEY_FILE_NEW_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_G_KEY_FILE_NEW_ERROR -204L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_G_MARKUP_PARSE_CONTEXT_NEW_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_G_MARKUP_PARSE_CONTEXT_NEW_ERROR -205L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_G_MARKUP_PARSE_CONTEXT_PARSE_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_G_MARKUP_PARSE_CONTEXT_PARSE_ERROR -206L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_G_PTR_ARRAY_REMOVE_INDEX_FAST_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_G_PTR_ARRAY_REMOVE_INDEX_FAST_ERROR -207L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_G_QUEUE_NEW_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_G_QUEUE_NEW_ERROR -208L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_G_STRDUP_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_G_STRDUP_ERROR -209L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_G_STRNDUP_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_G_STRNDUP_ERROR -210L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_G_STRSPLIT_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_G_STRSPLIT_ERROR -211L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_G_THREAD_CREATE_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_G_THREAD_CREATE_ERROR -212L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_G_TRY_MALLOC_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_G_TRY_MALLOC_ERROR -213L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_G_TRY_REALLOC_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_G_TRY_REALLOC_ERROR -214L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_GET_FIELD_ID_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_GET_FIELD_ID_ERROR -300L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_GET_OBJECT_CLASS_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_GET_OBJECT_CLASS_ERROR -301L
#undef org_tiian_flom_FlomErrorCodes_FLOM_RC_NEW_DIRECT_BYTE_BUFFER_ERROR
#define org_tiian_flom_FlomErrorCodes_FLOM_RC_NEW_DIRECT_BYTE_BUFFER_ERROR -302L
/*
 * Class:     org_tiian_flom_FlomErrorCodes
 * Method:    getText
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_tiian_flom_FlomErrorCodes_getText
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
