/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tiian_flom_FlomHandle */

#ifndef _Included_org_tiian_flom_FlomHandle
#define _Included_org_tiian_flom_FlomHandle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    newFH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_newFH
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    deleteFH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_deleteFH
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    lockFH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_lockFH
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    unlockFH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_unlockFH
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getLockedElementFH
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_tiian_flom_FlomHandle_getLockedElementFH
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getDiscoveryAttemptsFH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_getDiscoveryAttemptsFH
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setDiscoveryAttemptsFH
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_tiian_flom_FlomHandle_setDiscoveryAttemptsFH
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getDiscoveryTimeoutFH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_getDiscoveryTimeoutFH
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setDiscoveryTimeoutFH
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_tiian_flom_FlomHandle_setDiscoveryTimeoutFH
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getDiscoveryTtlFH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_getDiscoveryTtlFH
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setDiscoveryTtlFH
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_tiian_flom_FlomHandle_setDiscoveryTtlFH
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_tiian_flom_FlomException */

#ifndef _Included_org_tiian_flom_FlomException
#define _Included_org_tiian_flom_FlomException
#ifdef __cplusplus
extern "C" {
#endif
#undef org_tiian_flom_FlomException_serialVersionUID
#define org_tiian_flom_FlomException_serialVersionUID -3042686055658047285LL
#undef org_tiian_flom_FlomException_serialVersionUID
#define org_tiian_flom_FlomException_serialVersionUID -3387516993124229948LL
/*
 * Class:     org_tiian_flom_FlomException
 * Method:    getReturnCodeText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_tiian_flom_FlomException_getReturnCodeText
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
