/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tiian_flom_FlomHandle */

#ifndef _Included_org_tiian_flom_FlomHandle
#define _Included_org_tiian_flom_FlomHandle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    newJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_newJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    deleteJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tiian_flom_FlomHandle_deleteJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    lockJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_lockJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    unlockJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_unlockJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    unlockRollbackJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_unlockRollbackJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getLockedElementJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_tiian_flom_FlomHandle_getLockedElementJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getDiscoveryAttemptsJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_getDiscoveryAttemptsJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setDiscoveryAttemptsJNI
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setDiscoveryAttemptsJNI
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getDiscoveryTimeoutJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_getDiscoveryTimeoutJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setDiscoveryTimeoutJNI
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setDiscoveryTimeoutJNI
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getDiscoveryTtlJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_getDiscoveryTtlJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setDiscoveryTtlJNI
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setDiscoveryTtlJNI
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getLockModeJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_getLockModeJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setLockModeJNI
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setLockModeJNI
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getMulticastAddressJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_tiian_flom_FlomHandle_getMulticastAddressJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setMulticastAddressJNI
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setMulticastAddressJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getMulticastPortJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_getMulticastPortJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setMulticastPortJNI
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setMulticastPortJNI
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getNetworkInterfaceJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_tiian_flom_FlomHandle_getNetworkInterfaceJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setNetworkInterfaceJNI
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setNetworkInterfaceJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getResourceCreateJNI
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_tiian_flom_FlomHandle_getResourceCreateJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setResourceCreateJNI
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setResourceCreateJNI
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getResourceIdleLifespanJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_getResourceIdleLifespanJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setResourceIdleLifespanJNI
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setResourceIdleLifespanJNI
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getResourceNameJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_tiian_flom_FlomHandle_getResourceNameJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setResourceNameJNI
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setResourceNameJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getResourceQuantityJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_getResourceQuantityJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setResourceQuantityJNI
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setResourceQuantityJNI
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getResourceTimeoutJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_getResourceTimeoutJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setResourceTimeoutJNI
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setResourceTimeoutJNI
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getSocketNameJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_tiian_flom_FlomHandle_getSocketNameJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setSocketNameJNI
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setSocketNameJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getTraceFilenameJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_tiian_flom_FlomHandle_getTraceFilenameJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setTraceFilenameJNI
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setTraceFilenameJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getUnicastAddressJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_tiian_flom_FlomHandle_getUnicastAddressJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setUnicastAddressJNI
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setUnicastAddressJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getUnicastPortJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_getUnicastPortJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setUnicastPortJNI
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setUnicastPortJNI
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getTlsCertificateJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_tiian_flom_FlomHandle_getTlsCertificateJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setTlsCertificateJNI
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setTlsCertificateJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getTlsPrivateKeyJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_tiian_flom_FlomHandle_getTlsPrivateKeyJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setTlsPrivateKeyJNI
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setTlsPrivateKeyJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getTlsCaCertificateJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_tiian_flom_FlomHandle_getTlsCaCertificateJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setTlsCaCertificateJNI
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setTlsCaCertificateJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    getTlsCheckPeerIdJNI
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_tiian_flom_FlomHandle_getTlsCheckPeerIdJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_tiian_flom_FlomHandle
 * Method:    setTlsCheckPeerIdJNI
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_org_tiian_flom_FlomHandle_setTlsCheckPeerIdJNI
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
